src=$(wildcard *.c) 	# 选中所有.c
obj=$(patsubst %.c, %.o, $(src)) #替换为所有.c

ALL:main

main:$(obj)
	gcc $(obj) -o main

main.o:main.c
	gcc -c main.c -o main.o
add.o:add.c
	gcc -c add.c -o add.o
sub.o:sub.c
	gcc -c sub.c -o sub.o
multi.o:multi.c
	gcc -c multi.c -o multi.o
divi.o:main.c
	gcc -c divi.c -o divi.o

# 删除所有生成的文件
clean:
	-rm -rf $(obj) main
