src=$(wildcard *.c) 	# 选中所有.c
obj=$(patsubst %.c, %.o, $(src)) #替换为所有.c

ALL:main

main:$(obj)
	gcc $^ -o $@

main.o:main.c
	gcc -c $< -o $@
add.o:add.c
	gcc -c $< -o $@
sub.o:sub.c
	gcc -c $< -o $@
multi.o:multi.c
	gcc -c $< -o $@
divi.o:divi.c
	gcc -c $< -o $@

# 删除所有生成的文件
clean:
	-rm -rf $(obj) main
